<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Job;
use App\Models\User;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $companyUsers = User::where('account_type', 'company')
            ->where('role', '!=', 'guest')
            ->get();

        if ($companyUsers->isEmpty()) {
            $companyUsers = collect([User::where('role', '!=', 'guest')->first() ?? User::factory()->create()]);
        }

        $jobs = [
            // ── Ofertas de empresa real ──────────────────────────
            [
                'title' => 'Desarrollador Backend Laravel',
                'company_name' => 'Sofia',
                'description' => 'La empresa Tu Motico se encuentra en la búsqueda de un Desarrollador Backend especializado en Laravel para unirse a su equipo de tecnología. Trabajarás en el core de la plataforma, optimizando rendimiento y escalabilidad.',
                'requirements' => "• Experiencia mínima de 3 años con Laravel y PHP 8.x\n• Conocimiento sólido de MySQL y optimización de consultas\n• Experiencia con APIs RESTful\n• Familiaridad con Redis y colas\n• Git y flujo de trabajo colaborativo",
                'benefits' => "• Trabajo 100% remoto\n• Salario competitivo en USD\n• Horario flexible\n• Oportunidad de crecimiento",
                'application_url' => null,
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => null,
                'city' => null,
                'location' => 'Remoto',
                'seniority' => 'mid',
                'salary_min' => 1000,
                'salary_max' => 1100,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => '573046363941',
                'is_featured' => false,
                'status' => 'published',
            ],

            // ── Ofertas con datos completos ──────────────────────
            [
                'title' => 'Desarrollador Laravel Senior',
                'company_name' => 'TechCorp Latam',
                'description' => 'Buscamos un desarrollador Laravel senior para unirse a nuestro equipo de producto. Trabajarás en aplicaciones web escalables, APIs RESTful y sistemas de colas.',
                'requirements' => "• 5+ años de experiencia con PHP 8.x y Laravel\n• Experiencia con MySQL, Redis y colas\n• Conocimiento de arquitectura de microservicios\n• Pruebas automatizadas con PestPHP o PHPUnit\n• Experiencia con Docker",
                'benefits' => "• Salario en USD\n• Trabajo remoto desde cualquier lugar\n• Presupuesto anual de aprendizaje\n• Seguro de salud privado",
                'application_url' => 'https://techcorp.com/carreras/laravel-senior',
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => 'México',
                'city' => 'Remoto',
                'location' => 'Latinoamérica',
                'seniority' => 'senior',
                'salary_min' => 4500,
                'salary_max' => 6500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Frontend Developer React',
                'company_name' => 'InnovateTech',
                'description' => 'Únete a nuestro equipo de frontend para construir interfaces modernas con React, TypeScript y Tailwind CSS. Trabajarás en un producto SaaS usado por miles de usuarios en toda Latinoamérica.',
                'requirements' => "• 3+ años con React y TypeScript\n• Experiencia con Tailwind CSS y diseño responsive\n• Conocimiento de pruebas con Testing Library\n• Familiaridad con Next.js\n• Git y code review",
                'benefits' => "• Modelo híbrido en Bogotá\n• Viernes flexibles\n• Seguro médico\n• Bonos por desempeño",
                'application_url' => null,
                'location_type' => 'hybrid',
                'modality' => 'hibrido',
                'modality_label' => 'Híbrido',
                'country' => 'Colombia',
                'city' => 'Bogotá',
                'location' => 'Bogotá, Colombia',
                'seniority' => 'mid',
                'salary_min' => 3000,
                'salary_max' => 4500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => '573001234567',
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'DevOps Engineer',
                'company_name' => 'CloudSolutions',
                'description' => 'Buscamos un ingeniero DevOps para gestionar infraestructura en AWS, Kubernetes y pipelines CI/CD. Conocimiento en Docker, Terraform y monitoreo con Prometheus.',
                'requirements' => "• Experiencia con AWS (ECS, RDS, CloudFront)\n• Kubernetes en producción\n• Terraform o Pulumi\n• CI/CD con GitHub Actions o GitLab CI\n• Linux avanzado y scripting en Bash",
                'benefits' => "• Trabajo remoto\n• Horario flexible\n• Participación en acciones\n• Conferencias pagadas",
                'application_url' => 'https://cloudsolutions.io/careers/devops',
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => 'Argentina',
                'city' => 'Remoto',
                'location' => 'Latinoamérica',
                'seniority' => 'senior',
                'salary_min' => 5000,
                'salary_max' => 7500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Desarrollador Full Stack Python',
                'company_name' => 'DataDriven',
                'description' => 'Buscamos un desarrollador full stack con experiencia en Python (Django/FastAPI) y frontend moderno (React o Vue.js). Trabajarás en proyectos de data science e inteligencia artificial.',
                'requirements' => "• 3+ años con Python y Django/FastAPI\n• Experiencia con React o Vue.js\n• SQL y modelado de datos\n• APIs RESTful\n• Familiaridad con Docker",
                'benefits' => "• Trabajo presencial en Lima\n• Almuerzos cubiertos\n• Gym membresía\n• Seguro médico familiar",
                'application_url' => null,
                'location_type' => 'onsite',
                'modality' => 'presencial',
                'modality_label' => 'Presencial',
                'country' => 'Perú',
                'city' => 'Lima',
                'location' => 'Lima, Perú',
                'seniority' => 'mid',
                'salary_min' => 2500,
                'salary_max' => 4000,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => '51987123456',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Desarrollador Mobile Flutter',
                'company_name' => 'AppWorks',
                'description' => 'Buscamos un desarrollador mobile con experiencia en Flutter y Dart para crear aplicaciones multiplataforma. Conocimiento en Firebase, REST APIs y patrones de diseño BLoC.',
                'requirements' => "• 1+ año con Flutter y Dart\n• Conocimiento de Firebase\n• Consumo de APIs RESTful\n• Patrón BLoC o Riverpod\n• Publicación en App Store y Play Store",
                'benefits' => "• Trabajo remoto\n• Mentoría constante\n• Cursos pagados\n• Día libre de cumpleaños",
                'application_url' => null,
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => 'Chile',
                'city' => 'Remoto',
                'location' => 'Latinoamérica',
                'seniority' => 'junior',
                'salary_min' => 1500,
                'salary_max' => 2500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Backend Developer Node.js',
                'company_name' => 'APIFirst',
                'description' => 'Buscamos un desarrollador backend con experiencia en Node.js, Express y bases de datos SQL/NoSQL. Trabajarás en el desarrollo de APIs para aplicaciones de alto rendimiento.',
                'requirements' => "• 3+ años con Node.js\n• Experiencia con Express o NestJS\n• PostgreSQL y MongoDB\n• Diseño de APIs RESTful\n• Pruebas con Jest",
                'benefits' => "• Modelo híbrido en CDMX\n• Seguro de gastos médicos\n• Vales de despensa\n• Trabajo internacional",
                'application_url' => 'https://apifirst.dev/jobs/node-backend',
                'location_type' => 'hybrid',
                'modality' => 'hibrido',
                'modality_label' => 'Híbrido',
                'country' => 'México',
                'city' => 'Ciudad de México',
                'location' => 'Ciudad de México, México',
                'seniority' => 'mid',
                'salary_min' => 3500,
                'salary_max' => 5000,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'QA Automation Engineer',
                'company_name' => 'QualityFirst',
                'description' => 'Buscamos un ingeniero de QA con experiencia en automatización de pruebas usando Selenium, Cypress o Playwright. Conocimiento en CI/CD y pruebas de carga deseadas.',
                'requirements' => "• 2+ años en automatización de pruebas\n• Cypress o Playwright\n• Conocimiento de CI/CD\n• Pruebas de API con Postman\n• Inglés intermedio",
                'benefits' => "• Trabajo 100% remoto\n• Horario flexible\n• Bonos por productividad\n• Días extras de vacaciones",
                'application_url' => null,
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => 'Colombia',
                'city' => 'Remoto',
                'location' => 'Latinoamérica',
                'seniority' => 'mid',
                'salary_min' => 2000,
                'salary_max' => 3500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => '573009876543',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Data Engineer',
                'company_name' => 'DataCorp',
                'description' => 'Buscamos un data engineer para construir y mantener pipelines de datos, data warehouses y sistemas de ETL. Experiencia con Python, SQL, Spark y cloud platforms.',
                'requirements' => "• 4+ años como data engineer\n• Python y SQL avanzado\n• Apache Spark o similar\n• Cloud (AWS/GCP)\n• Modelado de datos dimensionales",
                'benefits' => "• Trabajo presencial en Santiago\n• Budget de aprendizaje\n• Seguro premium\n• Viernes de innovación",
                'application_url' => 'https://datacorp.cl/carreras/data-engineer',
                'location_type' => 'onsite',
                'modality' => 'presencial',
                'modality_label' => 'Presencial',
                'country' => 'Chile',
                'city' => 'Santiago',
                'location' => 'Santiago, Chile',
                'seniority' => 'senior',
                'salary_min' => 4500,
                'salary_max' => 6500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'title' => 'Desarrollador Junior PHP',
                'company_name' => 'WebStart',
                'description' => 'Buscamos un desarrollador junior con ganas de aprender y crecer en PHP y Laravel. Ideal para quienes están dando sus primeros pasos en el mundo laboral del desarrollo web.',
                'requirements' => "• Conocimientos básicos de PHP y MySQL\n• HTML, CSS y JavaScript\n• Familiaridad con Laravel o algún framework\n• Git básico\n• Actitud de aprendizaje",
                'benefits' => "• Programa de mentorship\n• Curso de Laravel pagado\n• Trabajo remoto\n• Posibilidad de contratación fija",
                'application_url' => null,
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => 'Uruguay',
                'city' => 'Remoto',
                'location' => 'Latinoamérica',
                'seniority' => 'junior',
                'salary_min' => 800,
                'salary_max' => 1200,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'title' => 'Tech Lead Golang',
                'company_name' => 'ScaleUp',
                'description' => 'Lidera el equipo de backend en su migración a Go. Buscamos un tech lead con experiencia en sistemas distribuidos y arquitectura de microservicios.',
                'requirements' => "• 7+ años de experiencia en desarrollo\n• 2+ años como tech lead\n• Go en producción\n• Sistemas distribuidos y mensajería (Kafka/RabbitMQ)\n• Inglés avanzado",
                'benefits' => "• Equity en la empresa\n• Trabajo remoto internacional\n• Presupuesto de conferencias\n• Seguro dental y médico",
                'application_url' => null,
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'country' => 'Colombia',
                'city' => 'Remoto',
                'location' => 'Latinoamérica',
                'seniority' => 'lead',
                'salary_min' => 7000,
                'salary_max' => 10000,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'whatsapp' => null,
                'is_featured' => true,
                'status' => 'published',
            ],
        ];

        foreach ($jobs as $data) {
            $data['user_id'] = $companyUsers->random()->id;
            $data['expires_at'] = now()->addDays(rand(15, 45));

            Job::create($data);
        }
    }
}
