<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $userId = \DB::table('users')->where('role', '!=', 'guest')->value('id') ?? 1;

        $jobs = [
            [
                'user_id' => $userId,
                'title' => 'Desarrollador Laravel Senior',
                'company_name' => 'TechCorp Latam',
                'description' => 'Buscamos un desarrollador Laravel senior para unirse a nuestro equipo de producto. Trabajarás en aplicaciones web escalables, APIs RESTful y sistemas de colas. Experiencia con PHP 8.x, Laravel 11, MySQL y Redis.',
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'location' => 'Latinoamérica',
                'country' => 'México',
                'city' => 'Remoto',
                'seniority' => 'senior',
                'salary_min' => 4500,
                'salary_max' => 6500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'Frontend Developer React',
                'company_name' => 'InnovateTech',
                'description' => 'Únete a nuestro equipo de frontend para construir interfaces modernas con React, TypeScript y Tailwind CSS. Trabajarás en un producto SaaS usado por miles de usuarios en toda Latinoamérica.',
                'location_type' => 'hybrid',
                'modality' => 'hibrido',
                'modality_label' => 'Híbrido',
                'location' => 'Bogotá, Colombia',
                'country' => 'Colombia',
                'city' => 'Bogotá',
                'seniority' => 'mid',
                'salary_min' => 3000,
                'salary_max' => 4500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => true,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'DevOps Engineer',
                'company_name' => 'CloudSolutions',
                'description' => 'Buscamos un ingeniero DevOps para gestionar infraestructura en AWS, Kubernetes y pipelines CI/CD. Conocimiento en Docker, Terraform y monitoreo con Prometheus.',
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'location' => 'Latinoamérica',
                'country' => 'Argentina',
                'city' => 'Remoto',
                'seniority' => 'senior',
                'salary_min' => 5000,
                'salary_max' => 7500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'Desarrollador Full Stack Python',
                'company_name' => 'DataDriven',
                'description' => 'Buscamos un desarrollador full stack con experiencia en Python (Django/FastAPI) y frontend moderno (React o Vue.js). Trabajarás en proyectos de data science e inteligencia artificial.',
                'location_type' => 'onsite',
                'modality' => 'presencial',
                'modality_label' => 'Presencial',
                'location' => 'Lima, Perú',
                'country' => 'Perú',
                'city' => 'Lima',
                'seniority' => 'mid',
                'salary_min' => 2500,
                'salary_max' => 4000,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'Desarrollador Mobile Flutter',
                'company_name' => 'AppWorks',
                'description' => 'Buscamos un desarrollador mobile con experiencia en Flutter y Dart para crear aplicaciones multiplataforma. Conocimiento en Firebase, REST APIs y patrones de diseño BLoC.',
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'location' => 'Latinoamérica',
                'country' => 'Chile',
                'city' => 'Remoto',
                'seniority' => 'junior',
                'salary_min' => 1500,
                'salary_max' => 2500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'Backend Developer Node.js',
                'company_name' => 'APIFirst',
                'description' => 'Buscamos un desarrollador backend con experiencia en Node.js, Express y bases de datos SQL/NoSQL. Trabajarás en el desarrollo de APIs para aplicaciones de alto rendimiento.',
                'location_type' => 'hybrid',
                'modality' => 'hibrido',
                'modality_label' => 'Híbrido',
                'location' => 'Ciudad de México, México',
                'country' => 'México',
                'city' => 'Ciudad de México',
                'seniority' => 'mid',
                'salary_min' => 3500,
                'salary_max' => 5000,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'QA Automation Engineer',
                'company_name' => 'QualityFirst',
                'description' => 'Buscamos un ingeniero de QA con experiencia en automatización de pruebas usando Selenium, Cypress o Playwright. Conocimiento en CI/CD y pruebas de carga deseadas.',
                'location_type' => 'remote',
                'modality' => 'remoto',
                'modality_label' => 'Remoto',
                'location' => 'Latinoamérica',
                'country' => 'Colombia',
                'city' => 'Remoto',
                'seniority' => 'mid',
                'salary_min' => 2000,
                'salary_max' => 3500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => false,
                'status' => 'published',
            ],
            [
                'user_id' => $userId,
                'title' => 'Data Engineer',
                'company_name' => 'DataCorp',
                'description' => 'Buscamos un data engineer para construir y mantener pipelines de datos, data warehouses y sistemas de ETL. Experiencia con Python, SQL, Spark y cloud platforms.',
                'location_type' => 'onsite',
                'modality' => 'presencial',
                'modality_label' => 'Presencial',
                'location' => 'Santiago, Chile',
                'country' => 'Chile',
                'city' => 'Santiago',
                'seniority' => 'senior',
                'salary_min' => 4500,
                'salary_max' => 6500,
                'currency' => 'usd',
                'salary_currency' => 'USD',
                'is_featured' => true,
                'status' => 'published',
            ],
        ];

        foreach ($jobs as $data) {
            Job::create($data);
        }
    }
}
