import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import path from "path";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                "resources/css/app.css",
                "resources/css/variables.css",
                "resources/css/auth/login.css",
                "resources/css/auth/register.css",
                "resources/css/auth/forgotPassword.css",
                "resources/css/auth/resetPassword.css",
                "resources/css/auth/twoFactor.css",
                "resources/css/shared/topbar.css",
                "resources/css/core/explore.css",
                "resources/css/core/notifications.css",
                "resources/css/core/messages.css",
                "resources/css/profile/shared.css",
                "resources/css/profile/sidebar.css",
                "resources/css/profile/profile.css",
                "resources/css/profile/workExperience.css",
                "resources/css/profile/cv.css",
                "resources/css/profile/modalImage.css",
                "resources/css/profile/notificationsProfile.css",
                "resources/css/settings/account.css",
                "resources/css/settings/security.css",
                "resources/css/settings/configuration.css",
                "resources/css/settings/privacy.css",
                "resources/css/settings/preferences.css",
                "resources/css/projects/newProject.css",
                "resources/css/projects/projectMedia.css",
                "resources/css/public/aboutFluxa.css",
                "resources/css/public/terms.css",
                "resources/css/public/privacyPolicy.css",
                "resources/css/public/contact.css",
                "resources/css/public/footer.css",
                "resources/css/onboarding/role.css",
                "resources/css/onboarding/technologies.css",
                "resources/css/onboarding/suggestions.css",
                "resources/css/admin/suggestions.css",
                "resources/js/app.js",
                "resources/js/shared/index.js",
                "resources/js/core/globals.js",
                "resources/js/profile/index.js",
                "resources/js/profile/avatar.js",
                "resources/js/profile/cv.js",
                "resources/js/profile/account.js",
                "resources/js/profile/configuration.js",
                "resources/js/profile/workExperience.js",
                "resources/js/profile/education.js",
                "resources/js/profile/commentHandler.js",
                "resources/js/shared/topbar.js",
                "resources/js/shared/toast.js",
                "resources/js/shared/passwordVisibility.js",
                "resources/js/shared/securePassword.js",
                "resources/js/shared/security.js",
                "resources/js/shared/modalScrollFix.js",
                "resources/js/core/explore/index.js",
                "resources/js/projects/modalComment.js",
                "resources/js/core/projects/newProject.js",
                "resources/js/core/projects/projectMedia.js",
                "resources/js/onboarding/index.js",
                "resources/js/onboarding/technologies.js",
                "resources/js/admin/index.js",
                "resources/js/core/messages/index.js",
            ],
            refresh: true,
        }),
    ],
});