import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                "resources/css/app.css",
                "resources/css/variables.css",
                "resources/css/profile/shared.css",
                "resources/css/login.css",
                "resources/css/register.css",
                "resources/css/forgotPassword.css",
                "resources/css/resetPassword.css",
                "resources/css/topbar.css",
                "resources/css/explore.css",
                "resources/css/newProject.css",
                "resources/css/notifications.css",
                "resources/css/pages/aboutFluxa.css",
                "resources/css/pages/terms.css",
                "resources/css/pages/privacyPolicy.css",
                "resources/css/pages/footer.css",
                "resources/css/role.css",
                "resources/css/technologies.css",
                "resources/css/suggestions.css",
                "resources/css/profile/profile.css",
                "resources/css/profile/sidebar.css",
                "resources/css/profile/security.css",
                "resources/css/profile/account.css",
                "resources/css/profile/configuration.css",
                "resources/css/profile/privacy.css",
                "resources/css/profile/preferences.css",
                "resources/css/profile/workExperience.css",
                "resources/css/profile/cv.css",
                "resources/css/profile/modalImage.css",
                "resources/css/suggestions/suggestions.css",
                "resources/css/projectMedia.css",
                "resources/css/twoFactor.css",
                "resources/js/app.js",
                "resources/js/explore/index.js",
                "resources/js/profile/index.js",
                "resources/js/profile/workExperience.js",
                "resources/js/profile/education.js",
                "resources/js/projects/index.js",
                "resources/js/projects/projectMedia.js",
                "resources/js/comments/index.js",
                "resources/js/shared/security.js",
                "resources/js/onboarding/index.js",
                "resources/js/shared/passwordVisibility.js",
                "resources/js/shared/securePassword.js",
                "resources/js/profile/account.js",
                "resources/js/profile/configuration.js",
                "resources/js/suggestions/index.js",
                "resources/js/shared/index.js",
                "resources/js/shared/topbar.js",
                "resources/js/shared/modalScrollFix.js",
                "resources/js/profile/avatar.js",
                "resources/js/profile/cv.js",
            ],
            refresh: true,
        }),
    ],
    server: {
        host: "0.0.0.0",
        port: 5173,
        hmr: {
            host: "localhost",
        },
    },
});
